### ISSUE TITLE
Level 37: The system cannot find the path specified.

### ISSUE THREAD

**Issue by miladamirzadeh** [Gazler/githug#214]
After completing level 36, level 37 description was followed by the sentence The system cannot find the path specified.

Typing githug reset have this output:
![screenshot 2016-07-16 16 29 11](https://cloud.githubusercontent.com/assets/7044707/16894668/a5848168-4b72-11e6-960b-afc818c8c089.png)

Thanks for your great game.

**Comment by miladamirzadeh** [comment]
Same thing on level 39.

**Comment by walker-zheng** [comment]
sh@sh-PC[mingw64]:git_hug(master) $ githug test push_branch
D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/githug-0.4.4/lib/githug/game.rb:38:in `test_level': undefined method `full_description' for false:FalseClass (NoMethodError)
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/githug-0.4.4/lib/githug/cli.rb:24:in `test'
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from D:/msys64/mingw64/lib/ruby/gems/2.3.0/gems/githug-0.4.4/bin/githug:4:in `<top (required)>'
        from D:/msys64/mingw64/bin/githug:23:in `load'
        from D:/msys64/mingw64/bin/githug:23:in `<main>'
********************************************************************************
*                                    Githug                                    *
********************************************************************************

**Comment by Gazler** [comment]
Thanks for the report. This could be a Windows specific issue. I don't have access to a Windows machine currently, I'll try to see what is going on with these 2 levels.

**Comment by pallxk** [comment]
It seems that shell commands with `2> /dev/null` in these levels do not run on Windows..

**Comment by usmanatron** [comment]
On Windows, /dev/null should instead be NUL I believe.  I'm going to have a go at fixing this!
